# Generated by Django 6.0.5 on 2026-05-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_fee_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_method',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_eta',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
