# Generated by Django 6.0.8 on 2026-08-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_delivery_method_order_delivery_eta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay (Test Mode)'), ('cod', 'Cash on Delivery')], default='razorpay', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('razorpay', 'Razorpay (Test Mode)'), ('cod', 'Cash on Delivery')], max_length=50),
        ),
    ]
