# Generated by Django 6.0.8 on 2026-09-04 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_idempotencyrecord_cart_cartitem_transactiondecision_and_more'),
        ('sellers', '0002_store_address_store_area_store_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order'),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_account', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('mode', models.CharField(choices=[('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('UPI', 'UPI')], default='NEFT', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('processed', 'Processed'), ('reversed', 'Reversed'), ('failed', 'Failed')], default='processed', max_length=20)),
                ('utr', models.CharField(blank=True, max_length=100)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='sellers.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('reason', models.CharField(choices=[('defective_product', 'Defective Product / Hardware Issue'), ('late_delivery', 'Late Delivery / Missed SLA'), ('customer_refusal', 'Customer Refusal / Changed Mind'), ('sizing_issue', 'Sizing / Fitment Mismatch'), ('duplicate_order', 'Duplicate Order Placed'), ('suspected_fraud', 'Suspected Fraud / Risk Intercept')], default='customer_refusal', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='processed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='orders.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Gross settlement volume', max_digits=12)),
                ('fees', models.DecimalField(decimal_places=2, default=0, help_text='Gateway fee deduction', max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, help_text='GST on gateway fee', max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Net credited amount', max_digits=12)),
                ('status', models.CharField(choices=[('created', 'Created'), ('processed', 'Processed'), ('delayed', 'Delayed'), ('failed', 'Failed')], default='processed', max_length=20)),
                ('utr', models.CharField(blank=True, max_length=100)),
                ('settlement_date', models.DateField()),
                ('is_delayed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='sellers.store')),
            ],
            options={
                'ordering': ['-settlement_date', '-created_at'],
            },
        ),
    ]
