# Generated by Django 6.0.5 on 2026-05-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.AddField(
            model_name='store',
            name='area',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='store',
            name='map_url',
            field=models.URLField(blank=True),
        ),
    ]
