# Generated by Django 6.0.5 on 2026-05-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_store_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_time_estimate',
            field=models.CharField(default='1-2 business days', max_length=100),
        ),
    ]
