# Generated by Django 6.0.5 on 2026-06-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional image URL for the review', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional video URL for the review', null=True),
        ),
    ]
