# Generated by Django 6.0.5 on 2026-06-04 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_review_image_url_review_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.CreateModel(
            name='ImageCurationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('good', 'Good'), ('could_be_better', 'Could be better'), ('wrong', 'Wrong')], max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curation_rating', to='products.product')),
            ],
        ),
    ]
