# Generated by Django 6.0.5 on 2026-06-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_increase_price_max_digits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
