# Generated by Django 6.0.8 on 2026-08-31 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_colors_product_cost_price_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.CharField(blank=True, help_text='Warehouse or storage location identifier.', max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='ai_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='AI-specific metadata (e.g., embedding model version, last vectorized timestamp).'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_paise',
            field=models.BigIntegerField(default=0, help_text='Cost price in paisa. Auto-computed from cost_price on save.'),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='NPR', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Semantic embedding vector (JSON fallback for non-PostgreSQL).', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='margin_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Gross margin percentage. Auto-computed: ((price - cost) / price) * 100.', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='price_paise',
            field=models.BigIntegerField(default=0, help_text='Selling price in paisa (1/100 of currency unit). Auto-computed from price on save.'),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_attributes', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
                'unique_together': {('product', 'key')},
            },
        ),
    ]
