# Generated by Django 6.0.8 on 2026-09-01 12:34

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_backfill_paise_margin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='embedding',
        ),
        migrations.AddField(
            model_name='product',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='Semantic embedding vector for AI-powered similarity search.', null=True),
        ),
    ]
