# Generated by Django 6.0.8 on 2026-09-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
