# Generated by Django 6.0.8 on 2026-08-30 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_product_colors_product_cost_price_product_sku_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_recommendations_enabled', models.BooleanField(default=True)),
                ('ai_checkout_enabled', models.BooleanField(default=True)),
                ('max_ai_order_value', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12)),
                ('max_ai_quantity', models.PositiveIntegerField(default=10)),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=999.0, max_digits=12)),
                ('risk_thresholds', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('campaign_type', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligible_products', models.ManyToManyField(blank=True, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('intent', models.CharField(max_length=100)),
                ('confidence', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('constraints', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.PositiveIntegerField(default=0)),
                ('velocity_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estimated_days_remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_insight', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=100, unique=True)),
                ('offer_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('redeemed', 'Redeemed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(related_name='offers', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='OfferDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=50)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('policy_version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='intelligence.offer')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_type', models.CharField(choices=[('upsell', 'Upsell'), ('cross_sell', 'Cross-sell'), ('bundle', 'Bundle'), ('stock_clearance', 'Stock Clearance'), ('abandoned_cart', 'Abandoned Cart')], max_length=50)),
                ('score', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('expected_revenue_impact', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_opportunities', to='products.product')),
                ('target_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('frequently_bought_with', 'Frequently Bought With'), ('alternative_to', 'Alternative To'), ('upgrade_to', 'Upgrade To'), ('accessory_for', 'Accessory For')], max_length=50)),
                ('source', models.CharField(help_text="e.g., 'system_generated', 'merchant_defined'", max_length=50)),
                ('confidence', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('merchant_defined', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='products.product')),
                ('target_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='products.product')),
            ],
            options={
                'unique_together': {('source_product', 'target_product', 'relationship_type')},
            },
        ),
    ]
