# Generated by Django 6.0.8 on 2026-08-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrelationship',
            name='relationship_type',
            field=models.CharField(choices=[('frequently_bought_with', 'Frequently Bought With'), ('alternative_to', 'Alternative To'), ('upgrade_to', 'Upgrade To'), ('accessory_for', 'Accessory For'), ('complementary', 'Complementary'), ('compatible', 'Compatible'), ('substitute', 'Substitute'), ('frequently_bought_together', 'Frequently Bought Together')], max_length=50),
        ),
    ]
