# Generated by Django 6.0.8 on 2026-09-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_expand_relationship_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('trace_id', models.CharField(blank=True, max_length=100)),
                ('agent', models.CharField(blank=True, max_length=64, null=True)),
                ('action', models.CharField(max_length=128)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50, unique=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('cart_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(default='Pending', max_length=32)),
                ('agent_action', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='merchantconfig',
            name='allow_ai_negotiation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchantconfig',
            name='auto_approval_threshold',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='merchantconfig',
            name='require_user_confirmation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='merchantconfig',
            name='max_discount_percent',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
    ]
