# Generated by Django 6.0.8 on 2026-09-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_auditevent_recoverytask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='auto_pause_at_budget',
            field=models.BooleanField(default=True, help_text='Automatically pause campaign when budget_limit is reached'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget_limit',
            field=models.DecimalField(decimal_places=2, default=50000.0, help_text='Budget cap for the campaign in INR', max_digits=12),
        ),
        migrations.AddField(
            model_name='campaign',
            name='current_spend',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total discount awarded so far in INR', max_digits=12),
        ),
        migrations.AddField(
            model_name='campaign',
            name='segments',
            field=models.JSONField(blank=True, default=list, help_text="Target customer segments e.g. ['high_value', 'cart_abandoners']"),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
