# Generated by Django 6.0.8 on 2026-09-04 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0004_campaign_auto_pause_at_budget_campaign_budget_limit_and_more'),
        ('orders', '0007_idempotencyrecord_cart_cartitem_transactiondecision_and_more'),
        ('sellers', '0002_store_address_store_area_store_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverytask',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_tasks', to='orders.order'),
        ),
        migrations.AddField(
            model_name='recoverytask',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_tasks', to='sellers.store'),
        ),
    ]
