# Generated by Django 6.0.8 on 2026-09-03 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('policy_type', models.CharField(choices=[('SPENDING_LIMIT', 'Financial Spending Limit'), ('RATE_LIMIT', 'Execution Rate Limit'), ('TOOL_ALLOWLIST', 'Allowed Tool Restraint'), ('DATA_ACCESS', 'Data Boundary Policy'), ('APPROVAL_RULE', 'Mandatory Approval Condition')], db_index=True, max_length=40)),
                ('rules', models.JSONField(default=dict, help_text='JSON rule definitions e.g. max_amount, allowed_tools')),
                ('violation_action', models.CharField(choices=[('BLOCK', 'Block Execution Immediately'), ('REQUIRE_APPROVAL', 'Halt and Require User Approval'), ('WARN_AND_LOG', 'Permit Action but Log Warning')], default='BLOCK', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Agent Policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(db_index=True, default='general', max_length=64)),
                ('parameters_schema', models.JSONField(default=dict, help_text='JSON Schema for input parameters')),
                ('required_permissions', models.JSONField(blank=True, default=list)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='LOW', max_length=20)),
                ('handler_path', models.CharField(blank=True, help_text='Dot-path to registered Python tool function', max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DISABLED', 'Disabled'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=20)),
                ('system_prompt', models.TextField(help_text='Core instructions, constraints, and identity for the agent')),
                ('approval_mode', models.CharField(choices=[('AUTO', 'Automatic Execution'), ('REVIEW_REQUIRED', 'Review Required on Risk/Policy'), ('ALWAYS_CONFIRM', 'Always Require User Confirmation'), ('BLOCKED', 'Execution Prohibited')], db_index=True, default='AUTO', max_length=30)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='LOW', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_agents', to=settings.AUTH_USER_MODEL)),
                ('policies', models.ManyToManyField(blank=True, related_name='agents', to='agent_runtime.agentpolicy')),
                ('tools', models.ManyToManyField(blank=True, related_name='agents', to='agent_runtime.agenttool')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentExecution',
            fields=[
                ('execution_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initial_request', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('WAITING_APPROVAL', 'Paused Waiting for Approval'), ('COMPLETED', 'Completed Successfully'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30)),
                ('current_step', models.CharField(blank=True, max_length=100)),
                ('output_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_trace', models.JSONField(blank=True, default=list, help_text='Chronological trace of runtime stages')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='agent_runtime.agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentAuditLog',
            fields=[
                ('audit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('EXECUTION_START', 'Execution Start'), ('INTENT_IDENTIFIED', 'Intent Identified'), ('TOOL_SELECTED', 'Tool Selected'), ('POLICY_CHECKED', 'Policy Checked'), ('APPROVAL_REQUIRED', 'Approval Required'), ('USER_APPROVED', 'User Approved'), ('USER_REJECTED', 'User Rejected'), ('TOOL_EXECUTED', 'Tool Executed'), ('RESULT_VALIDATED', 'Result Validated'), ('EXECUTION_COMPLETED', 'Execution Completed'), ('EXECUTION_FAILED', 'Execution Failed')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical Alert')], default='INFO', max_length=20)),
                ('actor_type', models.CharField(default='SYSTEM', max_length=30)),
                ('actor_id', models.CharField(blank=True, max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='agent_runtime.agent')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='agent_runtime.agentexecution')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentExecutionStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField()),
                ('step_type', models.CharField(choices=[('INTENT_PARSING', 'Intent Identified'), ('CONTEXT_GATHERING', 'Context Gathered'), ('PLAN_GENERATION', 'Tool Selected / Plan Created'), ('POLICY_EVALUATION', 'Policy Checked'), ('APPROVAL_CHECK', 'Approval Required / Handled'), ('TOOL_EXECUTION', 'Tool Executed'), ('RESULT_VALIDATION', 'Result Validated'), ('RESPONSE_GENERATION', 'Response Generated')], max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('WAITING_APPROVAL', 'Waiting Approval'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=30)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agent_runtime.agentexecution')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('execution', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='AgentApproval',
            fields=[
                ('approval_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_action', models.CharField(max_length=150)),
                ('action_payload', models.JSONField(default=dict)),
                ('reason', models.TextField(help_text='Policy justification or risk explanation for approval')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Decision'), ('APPROVED', 'Approved by User'), ('REJECTED', 'Rejected by User'), ('EXPIRED', 'Approval Window Expired')], db_index=True, default='PENDING', max_length=30)),
                ('decision_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='agent_runtime.agentexecution')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='agent_runtime.agentexecutionstep')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('trigger_type', models.CharField(choices=[('USER_REQUEST', 'Direct User Prompt'), ('EVENT', 'System Event'), ('SCHEDULE', 'Cron / Periodic Schedule'), ('WEBHOOK', 'External Webhook'), ('THRESHOLD', 'Metric Threshold Trigger')], default='USER_REQUEST', max_length=30)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='agent_runtime.agent')),
            ],
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_runtime.agenttrigger'),
        ),
        migrations.CreateModel(
            name='AgentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('system_prompt', models.TextField()),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('change_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='agent_runtime.agent')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('agent', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='agent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_runtime.agentversion'),
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('memory_type', models.CharField(choices=[('CONVERSATION', 'Conversational Dialog'), ('CONTEXT', 'Session Working Context'), ('PREFERENCE', 'User Preference'), ('ENTITY', 'Discovered Entity'), ('WORKING_STATE', 'Runtime Scratchpad')], default='CONVERSATION', max_length=30)),
                ('key', models.CharField(db_index=True, max_length=150)),
                ('value', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='agent_runtime.agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['agent', 'session_id', 'key'], name='agent_runti_agent_i_f2106b_idx'), models.Index(fields=['agent', 'user', 'key'], name='agent_runti_agent_i_42563a_idx')],
            },
        ),
    ]
