# Generated by Django 6.0.8 on 2026-09-03 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runtime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentapproval',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='agentapproval',
            name='is_double_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentapproval',
            name='merchant',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agentapproval',
            name='policy_triggered',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agentapproval',
            name='requires_double_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentapproval',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='AgentGovernancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Standard Agent Governance Policy', max_length=150)),
                ('max_transaction_amount', models.DecimalField(decimal_places=2, default=5000.0, max_digits=12)),
                ('daily_spend_limit', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12)),
                ('weekly_spend_limit', models.DecimalField(decimal_places=2, default=40000.0, max_digits=12)),
                ('monthly_spend_limit', models.DecimalField(decimal_places=2, default=150000.0, max_digits=12)),
                ('require_approval_above', models.DecimalField(decimal_places=2, default=2000.0, max_digits=12)),
                ('allowed_categories', models.JSONField(blank=True, default=list, help_text='Allowed categories, empty allows all non-blocked')),
                ('blocked_categories', models.JSONField(blank=True, default=list, help_text='Blocked categories e.g. electronics, cash, unknown')),
                ('allowed_merchants', models.JSONField(blank=True, default=list, help_text='Allowed merchants, empty allows all non-blocked')),
                ('blocked_merchants', models.JSONField(blank=True, default=list)),
                ('allowed_payment_methods', models.JSONField(blank=True, default=list)),
                ('allowed_hours', models.JSONField(blank=True, default=dict, help_text="e.g. {'start': '00:00', 'end': '23:59'}")),
                ('require_human_approval', models.BooleanField(default=False)),
                ('require_double_confirmation', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='governance_policy', to='agent_runtime.agent')),
            ],
        ),
        migrations.CreateModel(
            name='GovernanceDecisionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('ALLOW', 'Allow'), ('ALLOW_WITH_CONFIRMATION', 'Allow with Human Confirmation'), ('DENY', 'Deny'), ('ESCALATE', 'Escalate to Management')], db_index=True, max_length=40)),
                ('action', models.CharField(max_length=150)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('merchant', models.CharField(blank=True, max_length=150)),
                ('reason', models.TextField()),
                ('risk_score', models.FloatField(default=0.0)),
                ('policy_triggered', models.CharField(blank=True, max_length=150)),
                ('raw_prompt', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_records', to='agent_runtime.agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
