# Generated by Django 6.0.8 on 2026-09-03 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runtime', '0002_agentapproval_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentapproval',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='agent_runtime.agent'),
        ),
        migrations.AlterField(
            model_name='agentapproval',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='agent_runtime.agentexecution'),
        ),
    ]
