# Generated by Django 6.0.8 on 2026-09-03 11:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runtime', '0003_agentapproval_agent_alter_agentapproval_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentauditlog',
            name='event_type',
            field=models.CharField(choices=[('AGENT_CREATED', 'Agent Created'), ('AGENT_CONFIGURED', 'Agent Configured'), ('EXECUTION_START', 'Execution Start'), ('INTENT_IDENTIFIED', 'Intent Identified'), ('TOOL_SELECTED', 'Tool Selected'), ('POLICY_CHECKED', 'Policy Checked'), ('APPROVAL_REQUIRED', 'Approval Required'), ('USER_APPROVED', 'User Approved'), ('USER_REJECTED', 'User Rejected'), ('TOOL_EXECUTED', 'Tool Executed'), ('RESULT_VALIDATED', 'Result Validated'), ('EXECUTION_COMPLETED', 'Execution Completed'), ('EXECUTION_FAILED', 'Execution Failed')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='RefundAnomalyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_refund_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('baseline_refund_rate', models.DecimalField(decimal_places=2, default=Decimal('4.20'), max_digits=5)),
                ('delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('threshold_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('severity', models.CharField(default='LOW', max_length=20)),
                ('refund_count', models.PositiveIntegerField(default=0)),
                ('total_orders_count', models.PositiveIntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('affected_products', models.JSONField(blank=True, default=list)),
                ('by_product', models.JSONField(blank=True, default=list)),
                ('by_customer', models.JSONField(blank=True, default=list)),
                ('by_payment_method', models.JSONField(blank=True, default=list)),
                ('by_day', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True)),
                ('likely_reasons', models.JSONField(blank=True, default=list)),
                ('recommended_actions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_anomalies', to='agent_runtime.agent')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_anomalies', to='agent_runtime.agentexecution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
