# Generated by Django 6.0.8 on 2026-09-03 12:04

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runtime', '0004_alter_agentauditlog_event_type_refundanomalyrecord'),
        ('orders', '0007_idempotencyrecord_cart_cartitem_transactiondecision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentUserConsentPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('per_transaction_limit', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10)),
                ('approval_threshold', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=10)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10)),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=10)),
                ('allowed_categories', models.JSONField(default=list)),
                ('daily_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monthly_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_consent_policy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommercePaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cart_snapshot', models.JSONField(blank=True, default=dict)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant', models.CharField(default='RazorHub Direct', max_length=120)),
                ('product_summary', models.CharField(max_length=255)),
                ('payment_method', models.CharField(default='Razorpay UPI (Test Simulation)', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REQUIRES_CONFIRMATION', 'Requires Human Confirmation'), ('APPROVED', 'Approved by User'), ('REJECTED', 'Rejected by User'), ('EXECUTED', 'Executed Successfully'), ('BLOCKED', 'Blocked by Governance Policy')], default='PENDING', max_length=30)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('risk_level', models.CharField(default='LOW', max_length=20)),
                ('policy_triggered', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_payment_intents', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
