# Generated by Django 6.0.8 on 2026-09-03 12:15

import agent_runtime.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runtime', '0005_agentuserconsentpolicy_commercepaymentintent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPaymentAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_transaction_amount', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10)),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=10)),
                ('used_today', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('used_this_month', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('allowed_categories', models.JSONField(default=agent_runtime.models.default_auth_allowed_categories)),
                ('blocked_categories', models.JSONField(default=agent_runtime.models.default_auth_blocked_categories)),
                ('allowed_merchants', models.JSONField(default=agent_runtime.models.default_auth_allowed_merchants)),
                ('blocked_merchants', models.JSONField(default=list)),
                ('approval_threshold', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_reset_date', models.DateField(default=django.utils.timezone.now)),
                ('last_reset_month', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_authorizations', to='agent_runtime.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentAuthorizationLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=80)),
                ('decision', models.CharField(max_length=30)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('before_today', models.DecimalField(decimal_places=2, max_digits=10)),
                ('after_today', models.DecimalField(decimal_places=2, max_digits=10)),
                ('before_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('after_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='agent_runtime.agentpaymentauthorization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
