# Generated by Django 6.0.8 on 2026-09-03 12:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runtime', '0006_agentpaymentauthorization_agentauthorizationledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookkeepingEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_reference', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit (Expense / Outflow)'), ('CREDIT', 'Credit (Revenue / Inflow)')], max_length=20)),
                ('accounting_category', models.CharField(choices=[('REVENUE_SALES', 'Operating Revenue - E-Commerce Sales'), ('PAYROLL_CONTRACTORS', 'Operating Expense - Vendor & Contractor Payouts'), ('CLOUD_INFRASTRUCTURE', 'Technology - Cloud & Hosting Infrastructure'), ('SOFTWARE_LICENSES', 'Technology - Software & SaaS Subscriptions'), ('LOGISTICS_SHIPPING', 'Cost of Goods - Shipping & Fulfillment'), ('REFUND_EXPENSE', 'Contra Revenue - Customer Refunds'), ('TAX_GST', 'Taxes - Goods & Services Tax (GST)'), ('GENERAL_ADMIN', 'Administrative & Office Overhead')], max_length=50)),
                ('tax_deductible', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessFinanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('DAILY', 'Daily Finance Pulse'), ('WEEKLY', 'Weekly Treasury Summary'), ('MONTHLY', 'Monthly Comprehensive Report'), ('ANOMALY', 'Anomaly & Drift Diagnostic')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('metrics_snapshot', models.JSONField(default=dict)),
                ('narrative_summary', models.TextField()),
                ('anomalies_detected', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('vendor_or_customer', models.CharField(max_length=150)),
                ('invoice_type', models.CharField(choices=[('RECEIVABLE', 'Receivable (From Customer)'), ('PAYABLE', 'Payable (To Vendor)')], default='PAYABLE', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OVERDUE', 'Overdue'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='MEDIUM', max_length=20)),
                ('follow_up_count', models.PositiveIntegerField(default=0)),
                ('last_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('upi_vpa', models.CharField(blank=True, max_length=80)),
                ('category', models.CharField(default='General Services', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['due_date', '-amount'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS')], default='EMAIL', max_length=20)),
                ('message', models.TextField()),
                ('sent_by', models.CharField(default='Receivables Agent', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='agent_runtime.businessinvoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
