# Generated by Django 6.0.8 on 2026-09-03 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runtime', '0007_bookkeepingentry_businessfinancereport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.CharField(db_index=True, max_length=80, unique=True)),
                ('connector_type', models.CharField(choices=[('PaymentGateway', 'Payment Gateway'), ('Commerce', 'E-Commerce Platform'), ('Banking', 'Business Banking & Treasury'), ('Accounting', 'Accounting & General Ledger'), ('Communication', 'Messaging & Notifications'), ('Shipping', 'Logistics & Shipping'), ('Analytics', 'Data Warehouse & Analytics')], max_length=40)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ERROR', 'Configuration Error')], default='ACTIVE', max_length=20)),
                ('is_mock', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('config_schema', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['connector_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='connectors',
            field=models.ManyToManyField(blank=True, related_name='agents', to='agent_runtime.connector'),
        ),
        migrations.CreateModel(
            name='ConnectorCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('auth_type', models.CharField(choices=[('API_KEY', 'API Key'), ('BEARER_TOKEN', 'Bearer Token'), ('OAUTH2', 'OAuth 2.0'), ('BASIC_AUTH', 'HTTP Basic Auth'), ('MOCK', 'Mock Sandbox Secret')], default='MOCK', max_length=30)),
                ('encrypted_secret', models.TextField(blank=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='agent_runtime.connector')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability', models.CharField(max_length=20)),
                ('action_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('BLOCKED_BY_POLICY', 'Blocked by Agent Configuration')], default='SUCCESS', max_length=30)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connector_executions', to='agent_runtime.agent')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='agent_runtime.connector')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability', models.CharField(choices=[('READ', 'Read Data'), ('WRITE', 'Write Data'), ('SEND', 'Send Message / Event'), ('CREATE', 'Create Resource'), ('UPDATE', 'Update Resource'), ('DELETE', 'Delete Resource')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='agent_runtime.connector')),
            ],
            options={
                'ordering': ['connector', 'capability', 'name'],
                'unique_together': {('connector', 'name')},
            },
        ),
    ]
