# Generated by Django 6.0.8 on 2026-09-03 13:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runtime', '0008_connector_agent_connectors_connectorcredential_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS Text Message'), ('WHATSAPP', 'WhatsApp Business'), ('IN_APP', 'In-App Notification'), ('TELEGRAM', 'Telegram Channel / Bot')], max_length=20)),
                ('purpose', models.CharField(choices=[('TRANSACTIONAL', 'Transactional Notices'), ('MARKETING', 'Marketing & Promotional'), ('COLLECTIONS', 'Overdue Invoices & Collections'), ('SECURITY_ALERTS', 'Security & Anomaly Alerts'), ('ACCOUNT_UPDATES', 'Account & Policy Updates')], default='TRANSACTIONAL', max_length=40)),
                ('template_name', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=255)),
                ('rendered_content', models.TextField()),
                ('status', models.CharField(choices=[('DISPATCHED', 'Dispatched Successfully'), ('BLOCKED_NO_CONSENT', 'Blocked: Missing User Consent'), ('BLOCKED_OPTED_OUT', 'Blocked: User Opted Out'), ('BLOCKED_CHANNEL_DISABLED', 'Blocked: Channel Disabled by User'), ('BLOCKED_FREQUENCY_LIMIT', 'Blocked: Daily Frequency Limit Exceeded'), ('BLOCKED_AGENT_PERMISSION', 'Blocked: Agent Lacks Communication Permission'), ('FAILED', 'Provider Dispatch Failed')], default='DISPATCHED', max_length=40)),
                ('immutable_data', models.JSONField(blank=True, default=dict, help_text='Frozen financial/legal anchors')),
                ('blocked_reason', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_events', to='agent_runtime.agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('telegram_enabled', models.BooleanField(default=False)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=120)),
                ('is_opted_out_all', models.BooleanField(default=False)),
                ('daily_frequency_limit', models.PositiveIntegerField(default=5)),
                ('quiet_hours_start', models.PositiveIntegerField(default=22)),
                ('quiet_hours_end', models.PositiveIntegerField(default=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('TRANSACTIONAL', 'Transactional Notices'), ('MARKETING', 'Marketing & Promotional'), ('COLLECTIONS', 'Overdue Invoices & Collections'), ('SECURITY_ALERTS', 'Security & Anomaly Alerts'), ('ACCOUNT_UPDATES', 'Account & Policy Updates')], max_length=40)),
                ('is_granted', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-granted_at'],
                'unique_together': {('user', 'purpose')},
            },
        ),
    ]
