# Generated by Django 6.0.8 on 2026-09-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runtime', '0010_financialriskrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentexecution',
            name='approval_request',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='approval_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='context_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='final_action',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='input_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='intent',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='model_name',
            field=models.CharField(default='gemini-2.0-flash', max_length=100),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='policy_checks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='risk_checks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='timeline',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='token_usage',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='tool_inputs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='tool_results',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='tools_selected',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
