# Generated by Django 6.0.8 on 2026-09-04 10:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runtime', '0011_agentexecution_approval_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuserconsentpolicy',
            name='configured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentuserconsentpolicy',
            name='is_configured',
            field=models.BooleanField(default=False, help_text='True if the user has explicitly reviewed and saved their payment authorization rules'),
        ),
        migrations.AlterField(
            model_name='agentuserconsentpolicy',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('200000.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='agentuserconsentpolicy',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='agentuserconsentpolicy',
            name='per_transaction_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('150000.00'), max_digits=10),
        ),
    ]
